name: Go Server Build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-package:
    name: Build and Package Artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build Golang Server
      run: |
        cd backend
        go build -v -o server_linux ./server.go
        GOOS=darwin GOARCH=amd64 go build -v -o server_m1 ./server.go
        cd ..

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build
        cd ..

    - name: Prepare SQL Migrations
      run: |
        mkdir migrations
        cp -R backend/database/migrations/**/*.sql migrations/

    - name: Zip Artifacts
      run: zip -r release.zip backend/server frontend/dist migrations

    - name: Upload Artifacts Zip
      uses: actions/upload-artifact@v2
      with:
        name: bundled-artifacts
        path: release.zip
