name: Go Server Build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-package:
    name: Build and Package Artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build Golang Server
      run: |
        cd backend
        go build -v -o server_linux ./server.go
        GOOS=darwin GOARCH=amd64 go build -v -o server_m1 ./server.go
        cd ..

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build
        cd ..

    - name: Copy results to root folder
      run: |
        mkdir release
        mkdir release/frontend
        cp backend/server_linux release/
        cp backend/server_m1 release/
        cp -r frontend/dist/* release/frontend
        cp -r backend/database/migrations release/
        
    - name: Upload artifacts zip
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: |
          release/*
