name: Go Server Build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build
      run: |
        cd backend
        go build -v -o server_linux ./server.go
        GOOS=darwin GOARCH=amd64 go build -v -o server_m1 ./server.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: backend/server
  
  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build
      run: npm run build
      working-directory: ./frontend

  build-and-package:
    name: Build and Package Artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Golang Server
      run: |
        cd backend
        GOOS=darwin GOARCH=amd64 go build -v -o server ./main.go
        cd ..

    - name: Build Vue3 Frontend
      run: |
        cd frontend
        npm install
        npm run build
        cd ..

    - name: Prepare SQL Migrations
      run: |
        mkdir migrations
        cp -R database/migrations/**/*.sql migrations/

    - name: Zip Artifacts
      run: zip -r artifacts.zip backend/server frontend/dist migrations

    - name: Upload Artifacts Zip
      uses: actions/upload-artifact@v2
      with:
        name: bundled-artifacts
        path: release.zip
